eureka:
  client:
    service-url:
      defaultZone: https://minhtn36.io.vn:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://rds-db.chh6klcv46jr.ap-southeast-1.rds.amazonaws.com:3306/userdb
    password: rdsuser
    username: rdssecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect